image: tiangolo/docker-with-compose

variables:
  COMMIT_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  GIT_SSL_NO_VERIFY: "true"
  DOCKER_DRIVER: overlay2


services:
 - docker:dind

stages:
  - build

.build: &build
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t $COMMIT_IMAGE .
    - docker push $COMMIT_IMAGE

build:auto:
  <<: *build
  only:
    - master
  except:
    - schedules

build:manual:
  <<: *build
  when: manual
  except:
    - master
    - schedules
